name = "aoc_2024"
version = "1.0.0"
licenses = [ "GPL-3.0-or-later" ]
repository = { type = "github", user = "tiborpilz", repo = "aoc_2024" }
description = "Solutions for 2024's Advent of Code"

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.32.0 and < 1.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
glint = ">= 1.1.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_community_ansi = ">= 1.4.2 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gleam_otp = ">= 0.16.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
